// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Icon = require("office-ui-fabric-react/lib/Icon");
var Button = require("office-ui-fabric-react/lib/Button");
var Fabric = require("office-ui-fabric-react/lib/Fabric");
var Persona = require("office-ui-fabric-react/lib/Persona");
var SearchBox = require("office-ui-fabric-react/lib/SearchBox");
var TextField = require("office-ui-fabric-react/lib/TextField");
var DocumentCard = require("office-ui-fabric-react/lib/DocumentCard");

function createIconProps(iconName) {
  return {
          iconName: iconName
        };
}

function make(children) {
  return ReasonReact.wrapJsForReason(Fabric.Fabric, { }, children);
}

var Fabric$1 = /* module */[/* make */make];

function toJs(t) {
  if (t >= -87349308) {
    if (t >= 459971812) {
      if (t >= 845958041) {
        if (t >= 887873852) {
          return 9;
        } else {
          return 0;
        }
      } else if (t >= 626048343) {
        return 7;
      } else {
        return 2;
      }
    } else if (t !== -20118752) {
      if (t >= 244774657) {
        return 3;
      } else {
        return 13;
      }
    } else {
      return 5;
    }
  } else if (t >= -607770705) {
    if (t >= -415342130) {
      if (t >= -278924591) {
        return 12;
      } else {
        return 6;
      }
    } else if (t >= -474806229) {
      return 8;
    } else {
      return 10;
    }
  } else if (t !== -837378486) {
    if (t >= -825337610) {
      return 11;
    } else {
      return 4;
    }
  } else {
    return 1;
  }
}

var DirectionalHint = /* module */[/* toJs */toJs];

function _createItem(key, name, onClick) {
  return {
          key: key,
          name: name,
          onClick: onClick
        };
}

function createItems(items) {
  return $$Array.of_list(List.map((function (item) {
                    return _createItem(item[/* key */0], item[/* name */1], item[/* onClick */2]);
                  }), items));
}

function createMenuProps(shouldFocusOnMount, directionalHint, items) {
  return {
          shouldFocusOnMount: shouldFocusOnMount,
          directionalHint: toJs(directionalHint),
          items: items
        };
}

var MenuProps = /* module */[
  /* _createItem */_createItem,
  /* createItems */createItems,
  /* createMenuProps */createMenuProps
];

var ButtonUtils = /* module */[
  /* DirectionalHint */DirectionalHint,
  /* MenuProps */MenuProps
];

function make$1(text, primary, disabled, iconProps, onClick, menuProps, children) {
  return ReasonReact.wrapJsForReason(Button.DefaultButton, {
              text: Js_null_undefined.fromOption(text),
              primary: Js_null_undefined.fromOption(primary),
              disabled: Js_null_undefined.fromOption(disabled),
              iconProps: Js_null_undefined.fromOption(iconProps),
              onClick: Js_null_undefined.fromOption(onClick),
              menuProps: Js_null_undefined.fromOption(menuProps)
            }, children);
}

var DefaultButton = /* module */[/* make */make$1];

function make$2(value, label, disabled, required, errorMessage, ariaLabel, placeholder, borderless, className, type_, componentRef, _, deferredValidationTime, description, iconProps, inputClassName, multiline, onBeforeChange, onChanged, onGetErrorMessage, onNotifyValidationResult, prefix, resizable, suffix, underlined, children) {
  return ReasonReact.wrapJsForReason(TextField.TextField, {
              value: Js_null_undefined.fromOption(value),
              label: Js_null_undefined.fromOption(label),
              disabled: Js_null_undefined.fromOption(disabled),
              required: Js_null_undefined.fromOption(required),
              errorMessage: Js_null_undefined.fromOption(errorMessage),
              ariaLabel: Js_null_undefined.fromOption(ariaLabel),
              placeholder: Js_null_undefined.fromOption(placeholder),
              borderless: Js_null_undefined.fromOption(borderless),
              className: Js_null_undefined.fromOption(className),
              type: Js_null_undefined.fromOption(type_),
              componentRef: Js_null_undefined.fromOption(componentRef),
              deferredValidationTime: Js_null_undefined.fromOption(deferredValidationTime),
              description: Js_null_undefined.fromOption(description),
              iconProps: Js_null_undefined.fromOption(iconProps),
              inputClassName: Js_null_undefined.fromOption(inputClassName),
              multiline: Js_null_undefined.fromOption(multiline),
              onBeforeChange: Js_null_undefined.fromOption(onBeforeChange),
              onChanged: Js_null_undefined.fromOption(onChanged),
              onGetErrorMessage: Js_null_undefined.fromOption(onGetErrorMessage),
              onNotifyValidationResult: Js_null_undefined.fromOption(onNotifyValidationResult),
              prefix: Js_null_undefined.fromOption(prefix),
              suffix: Js_null_undefined.fromOption(suffix),
              resizable: Js_null_undefined.fromOption(resizable),
              underlined: Js_null_undefined.fromOption(underlined)
            }, children);
}

var TextField$1 = /* module */[/* make */make$2];

function make$3(children) {
  return ReasonReact.wrapJsForReason(DocumentCard.DocumentCard, { }, children);
}

var DocumentCard$1 = /* module */[/* make */make$3];

function make$4(children) {
  return ReasonReact.wrapJsForReason(DocumentCard.IDocumentCardPreviewProps, { }, children);
}

var IDocumentCardPreviewProps = /* module */[/* make */make$4];

var previewPropsUsingIcon = {
  previewImages: /* :: */[
    {
      previewIconProps: {
        iconName: "OpenFile",
        styles: {
          root: {
            fontSize: 42,
            color: "#ffffff"
          }
        }
      },
      width: 318,
      height: 196
    },
    /* [] */0
  ]
};

function make$5($staropt$star, children) {
  var previewImages = $staropt$star ? $staropt$star[0] : previewPropsUsingIcon.previewImages;
  return ReasonReact.wrapJsForReason(DocumentCard.DocumentCardPreview, {
              previewImages: previewImages
            }, children);
}

var DocumentCardPreview = /* module */[
  /* previewPropsUsingIcon */previewPropsUsingIcon,
  /* make */make$5
];

function make$6(title, shouldTruncate, children) {
  return ReasonReact.wrapJsForReason(DocumentCard.DocumentCardTitle, {
              title: title,
              shouldTruncate: Js_null_undefined.fromOption(shouldTruncate)
            }, children);
}

var DocumentCardTitle = /* module */[/* make */make$6];

var people_000 = {
  name: "Kat Larrson"
};

var people = /* :: */[
  people_000,
  /* [] */0
];

function make$7(activity, children) {
  return ReasonReact.wrapJsForReason(DocumentCard.DocumentCard, {
              activity: activity,
              people: people
            }, children);
}

var DocumentCardActivity = /* module */[
  /* people */people,
  /* make */make$7
];

function make$8(iconName, className, styles, children) {
  return ReasonReact.wrapJsForReason(Icon.Icon, {
              iconName: iconName,
              className: Js_null_undefined.fromOption(className),
              styles: Js_null_undefined.fromOption(styles)
            }, children);
}

var Icon$1 = /* module */[/* make */make$8];

function make$9(imageUrl, primaryText, secondaryText, imageInitials, showSecondaryText, style, children) {
  return ReasonReact.wrapJsForReason(Persona.Persona, {
              imageUrl: Js_null_undefined.fromOption(imageUrl),
              primaryText: Js_null_undefined.fromOption(primaryText),
              secondaryText: Js_null_undefined.fromOption(secondaryText),
              imageInitials: Js_null_undefined.fromOption(imageInitials),
              showSecondaryText: Js_null_undefined.fromOption(showSecondaryText),
              styles: Js_null_undefined.fromOption(style)
            }, children);
}

var Persona$1 = /* module */[/* make */make$9];

function make$10(placeholder, children) {
  return ReasonReact.wrapJsForReason(SearchBox.SearchBox, {
              placeholder: Js_null_undefined.fromOption(placeholder)
            }, children);
}

var SearchBox$1 = /* module */[/* make */make$10];

exports.createIconProps = createIconProps;
exports.Fabric = Fabric$1;
exports.ButtonUtils = ButtonUtils;
exports.DefaultButton = DefaultButton;
exports.TextField = TextField$1;
exports.DocumentCard = DocumentCard$1;
exports.IDocumentCardPreviewProps = IDocumentCardPreviewProps;
exports.DocumentCardPreview = DocumentCardPreview;
exports.DocumentCardTitle = DocumentCardTitle;
exports.DocumentCardActivity = DocumentCardActivity;
exports.Icon = Icon$1;
exports.Persona = Persona$1;
exports.SearchBox = SearchBox$1;
/* ReasonReact Not a pure module */
